---
kind: pipeline
type: docker
name: build-pr

platform:
  os: linux
  arch: amd64

steps:
- name: initialize
  image: srclosson/grafana-plugin-ci-alpine:latest
  commands:
  - yarn install
  - cp -r $(yarn cache dir) yarn-cache

- name: build_frontend
  image: srclosson/grafana-plugin-ci-alpine:latest
  commands:
  - rm -rf $(yarn cache dir) && cp -r yarn-cache $(yarn cache dir)
  - ./node_modules/.bin/grafana-toolkit plugin:ci-build
  - ./node_modules/.bin/grafana-toolkit plugin:ci-build --finish
  depends_on:
  - initialize
