config:
  line-length:
    line_length: 120
    tables: false
  no-duplicate-heading:
    siblings_only: true
ignores:
  - CLAUDE.md
  - node_modules
  - dist
  - playwright-report
  - .config
  - docs
  - README.md
  - test-results
  - provisioning
