grafana:
  #image: grafana/grafana:latest
  #image: grafana/grafana:7.5.8
  image: grafana/grafana:7.3.0
  ports:
    - "3000:3000"
  volumes:
    - ./dist:/var/lib/grafana/plugins/grafana-polystat-panel
    - ./provisioning:/etc/grafana/provisioning
  environment:
    - TERM=linux
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-polystat-panel
