version: "3"
services:
  grafana:
    #image: grafana/grafana:latest
    #image: grafana/grafana:9.0.0
    image: grafana/grafana:7.3.10
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-polystat-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-polystat-panel
    #  - GF_INSTALL_PLUGINS=grafana-polystat-panel
