import { PolygonShapes, PolystatModel, PolystatOptions, TimestampPositions } from '../components/types';

// fixtures share one fixed instant so anything rendering a timestamp stays deterministic
export const FIXTURE_TIMESTAMP = new Date('01 October 2022 10:28 UTC').getTime();

/**
 * Builds a PolystatModel without going through a DataFrame, for tests that need to set
 * individual fields. Defaults are neutral, override whatever the test is about.
 */
export const createPolystatModel = (overrides: Partial<PolystatModel> = {}): PolystatModel => ({
  displayMode: 'all',
  thresholdLevel: 0,
  value: 0,
  valueFormatted: '0',
  valueRounded: 0,
  stats: {},
  name: 'metric',
  displayName: 'metric',
  timestamp: FIXTURE_TIMESTAMP,
  timestampFormatted: '',
  prefix: '',
  suffix: '',
  color: '#000000',
  clickThrough: '',
  operatorName: 'mean',
  newTabEnabled: false,
  customClickthroughTargetEnabled: false,
  customClickthroughTarget: '',
  sanitizedURL: '',
  sanitizeURLEnabled: false,
  showName: true,
  showValue: true,
  showTimestamp: false,
  isComposite: false,
  members: [],
  ...overrides,
});

/**
 * Builds a complete PolystatOptions for tests that render <Polystat/> directly.
 * Values mirror the panel defaults; override whatever the test is about.
 */
export const createPolystatOptions = (overrides: Partial<PolystatOptions> = {}): PolystatOptions => ({
  autoSizeColumns: true,
  autoSizeRows: true,
  autoSizePolygons: true,
  ellipseCharacters: 18,
  ellipseEnabled: false,
  globalAutoScaleFonts: true,
  globalClickthrough: '',
  globalClickthroughNewTabEnabled: false,
  globalClickthroughSanitizedEnabled: true,
  globalClickthroughCustomTargetEnabled: false,
  globalClickthroughCustomTarget: '',
  globalDecimals: 2,
  globalDisplayMode: 'all',
  globalDisplayTextTriggeredEmpty: 'OK',
  globalFillColor: '#0a55a1',
  globalLabelFontSize: 12,
  globalValueFontSize: 12,
  globalCompositeValueFontSize: 12,
  globalGradientsEnabled: false,
  globalOperator: 'mean',
  globalPolygonBorderSize: 0,
  globalPolygonBorderColor: '#000000',
  globalPolygonSize: '50',
  globalRegexPattern: '',
  globalShape: PolygonShapes.HEXAGON_POINTED_TOP,
  globalShowValueEnabled: true,
  globalShowTimestampEnabled: false,
  globalShowTimestampFormat: 'YYYY-MM-DD HH:mm:ss',
  globalShowTimestampFontSize: 12,
  globalShowTimestampPosition: TimestampPositions.BELOW_VALUE,
  globalShowTimestampYOffset: 0,
  globalShowTooltipColumnHeadersEnabled: true,
  globalTextFontAutoColor: '#000000',
  globalTextFontAutoColorEnabled: false,
  globalTextFontColor: '#FFFFFF',
  globalTextFontFamily: 'Inter',
  globalThresholdsConfig: [],
  globalTooltipsEnabled: false,
  globalTooltipsShowTimestampEnabled: false,
  globalTooltipsShowValueEnabled: true,
  globalTooltipsFontFamily: 'Inter',
  globalUnitFormat: 'short',
  layoutDisplayLimit: 100,
  layoutNumColumns: 8,
  layoutNumRows: 8,
  processedData: [],
  panelHeight: 200,
  panelWidth: 800,
  panelId: 1,
  radius: null,
  sortByField: 'name',
  sortByDirection: 1,
  overrideConfig: { overrides: [] },
  compositeGlobalAliasingEnabled: false,
  compositeConfig: { animationSpeed: '5000', composites: [], enabled: false },
  tooltipPrimarySortDirection: 1,
  tooltipPrimarySortByField: 'name',
  tooltipSecondarySortDirection: 1,
  tooltipSecondarySortByField: 'name',
  tooltipDisplayMode: 'all',
  tooltipDisplayTextTriggeredEmpty: 'OK',
  ...overrides,
});
